from typing import TYPE_CHECKING

#
# def calculate_revenue_for_variant(
#     variant: "ProductVariant", start_date: Union["date", "datetime"]
# ):
#     """Calculate total revenue generated by a product variant."""
#     revenue = zero_taxed_money()
#     for order_line in variant.order_lines.all():
#         if order_line.order.created >= start_date:
#             net = order_line.unit_price_net * order_line.quantity
#             gross = order_line.unit_price_gross * order_line.quantity
#             revenue += TaxedMoney(net, gross)
#     return revenue
