# Generated by Django 3.0.6 on 2020-07-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200602_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='company_name',
        ),
    ]
