# Generated by Django 3.0.6 on 2020-05-10 07:49
from django.core.management import call_command

from django.db import migrations

fixture_province = "fetch_province"
fixture_city = "fetch_city"
fixture_sub_district = "fetch_subdistrict"


def load_fixture(apps, schema_editor):
    call_command("loaddata", fixture_province, app_label="regions")
    call_command("loaddata", fixture_city, app_label="regions")
    call_command("loaddata", fixture_sub_district, app_label="regions")


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_fixture)]
