# Generated by Django 3.0.6 on 2020-06-29 21:25

import draftjs_sanitizer
from django.db import migrations

import core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="page", name="content_json",),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=core.db.fields.SanitizedJSONField(
                blank=True, default=dict, sanitizer=draftjs_sanitizer.clean_draft_js
            ),
        ),
    ]
