# Generated by Django 3.0.6 on 2020-07-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginconfiguration',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='pluginconfiguration',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
