# Generated by Django 3.0.6 on 2020-07-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_auto_20200714_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginconfiguration',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
