# Generated by Django 3.0.6 on 2020-06-18 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0004_auto_20200619_0048"),
        ("products", "0003_auto_20200611_1629"),
        ("collections", "0002_auto_20200611_1629"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("entire_order", "Entire order"),
                            ("shipping", "Shipping"),
                            ("specific_product", "Specific products, collections and categories"),
                        ],
                        default="entire_order",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("code", models.CharField(db_index=True, max_length=12, unique=True)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("used", models.PositiveIntegerField(default=0, editable=False)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("apply_once_per_order", models.BooleanField(default=False)),
                ("apply_once_per_customer", models.BooleanField(default=False)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("fixed", "RP"), ("percentage", "%")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                ("discount_value", models.PositiveIntegerField(default=0)),
                ("min_spent_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_checkout_items_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("categories", models.ManyToManyField(blank=True, to="categories.Category")),
                ("collections", models.ManyToManyField(blank=True, to="collections.Collection")),
                ("products", models.ManyToManyField(blank=True, to="products.Product")),
            ],
            options={
                "ordering": ("code",),
                "permissions": (("manage_discounts", "Manage sales and vouchers."),),
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("fixed", "RP"), ("percentage", "%")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("categories", models.ManyToManyField(blank=True, to="categories.Category")),
                ("collections", models.ManyToManyField(blank=True, to="collections.Collection")),
                ("products", models.ManyToManyField(blank=True, to="products.Product")),
            ],
            options={"ordering": ("name", "pk"),},
        ),
        migrations.CreateModel(
            name="VoucherCustomer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="discounts.Voucher",
                    ),
                ),
            ],
            options={
                "ordering": ("voucher", "customer_email"),
                "unique_together": {("voucher", "customer_email")},
            },
        ),
    ]
