# Generated by Django 3.0.6 on 2020-06-21 01:16

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_remove_voucher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=12, unique=True),
        ),
    ]
