# Generated by Django 3.0.6 on 2020-06-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20200621_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='min_checkout_items_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_spent_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
