# Generated by Django 3.0.6 on 2020-06-01 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('track_inventory_by_default', models.BooleanField(default=True)),
                ('automatic_fulfillment_digital_products', models.BooleanField(default=False)),
                ('default_digital_max_downloads', models.IntegerField(blank=True, null=True)),
                ('default_digital_url_valid_days', models.IntegerField(blank=True, null=True)),
                ('default_mail_sender_name', models.CharField(blank=True, default='', max_length=78, validators=[django.core.validators.RegexValidator('[\\n\\r]', inverse_match=True, message='New lines are not allowed.'), django.core.validators.MaxLengthValidator(78)])),
                ('default_mail_sender_address', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'permissions': (('manage_settings', 'Manage settings'),),
            },
        ),
    ]
