# Generated by Django 3.0.6 on 2020-07-14 06:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizationKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook-Oauth2"),
                            ("google-oauth2", "Google-Oauth2"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.TextField()),
                ("password", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("header_text", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("track_inventory_by_default", models.BooleanField(default=True)),
                (
                    "default_mail_sender_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=78,
                        validators=[
                            django.core.validators.RegexValidator(
                                "[\\n\\r]",
                                inverse_match=True,
                                message="New lines are not allowed.",
                            ),
                            django.core.validators.MaxLengthValidator(78),
                        ],
                    ),
                ),
                ("default_mail_sender_address", models.EmailField(blank=True, max_length=254)),
                ("customer_set_password_url", models.CharField(blank=True, max_length=255)),
                (
                    "bottom_menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="menus.Menu",
                    ),
                ),
            ],
            options={"permissions": (("manage_settings", "Manage settings"),),},
        ),
    ]
