# Generated by Django 3.0.6 on 2020-07-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0003_set_site_domain_and_name"),
        ("menus", "0001_initial"),
        ("collections", "0001_initial"),
        ("site", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="company_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.Address",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="homepage_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="collections.Collection",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="sites.Site",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="top_menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="menus.Menu",
            ),
        ),
        migrations.AddField(
            model_name="authorizationkey",
            name="site_settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="site.SiteSettings"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="authorizationkey", unique_together={("site_settings", "name")},
        ),
    ]
