# Generated by Django 3.0.6 on 2020-06-01 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("site", "0001_initial"),
        ("sites", "0003_set_site_domain_and_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="company_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.Address",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="sites.Site",
            ),
        ),
    ]
