# Generated by Django 3.0.6 on 2020-07-14 06:03
from django.db import migrations


def link_to_sites(apps, _schema_editor):
    SiteSettings = apps.get_model("site", "SiteSettings")
    Site = apps.get_model("sites", "Site")

    for site in Site.objects.filter(settings__isnull=True):
        SiteSettings.objects.get_or_create(
            site=site, defaults={"header_text": "Test Saleor - a sample shop!"}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0002_auto_20200714_1302"),
    ]

    operations = [
        migrations.RunPython(link_to_sites, migrations.RunPython.noop),
    ]
