# Generated by Django 3.0.6 on 2020-07-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0004_auto_20200620_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='automatic_fulfillment_digital_products',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='default_digital_max_downloads',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='default_digital_url_valid_days',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='customer_set_password_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
