# Generated by Django 3.0.6 on 2020-07-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0006_authorizationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='customer_set_password_url',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_mail_sender_address',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
    ]
