# Generated by Django 3.0.6 on 2020-07-14 06:02

import django.contrib.postgres.fields.jsonb
import django.core.validators
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models

import core.utils.images


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        validators=[django.core.validators.MaxLengthValidator(70)],
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        validators=[django.core.validators.MaxLengthValidator(300)],
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "description",
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
                ),
                (
                    "background_image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.images.UploadToPathAndRename(
                            field="name", path="category-backgrounds"
                        ),
                    ),
                ),
                ("background_image_alt", models.CharField(blank=True, max_length=128)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="categories.Category",
                    ),
                ),
            ],
            options={"permissions": (("manage_categories", "Manage categories"),),},
        ),
    ]
