# Generated by Django 3.0.6 on 2020-06-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='background',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='background_alt',
            new_name='background_image_alt',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_json',
            new_name='description',
        ),
    ]
