# Generated by Django 3.0.6 on 2020-06-18 17:48

import versatileimagefield.fields
from django.db import migrations

import core.utils.images


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_auto_20200611_1629"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="background_image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=core.utils.images.UploadToPathAndRename(
                    field="name", path="category-backgrounds"
                ),
            ),
        ),
    ]
