# Generated by Django 3.0.6 on 2020-07-14 06:02

import django.contrib.postgres.fields.citext
from django.db import migrations, models

import anphene.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    django.contrib.postgres.fields.citext.CICharField(max_length=150, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    anphene.users.models.PossiblePhoneNumberField(
                        blank=True, default="", max_length=128, region=None
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
            ],
            options={"permissions": (("manage_suppliers", "Manage suppliers"),),},
        ),
    ]
