# Generated by Django 3.0.6 on 2020-06-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ("pk",),
                "permissions": (("manage_menus", "Manage navigation."),),
            },
        ),
    ]
