# Generated by Django 3.0.6 on 2020-06-09 08:36

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='slug',
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=250, unique=True),
        ),
    ]
