# Generated by Django 3.0.6 on 2020-06-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200611_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimal_variant_price',
        ),
    ]
