# Generated by Django 3.0.6 on 2020-06-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_minimal_variant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
