# Generated by Django 3.0.6 on 2020-06-28 14:19

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productvariant_name"),
    ]

    operations = [TrigramExtension()]
