# Generated by Django 3.0.6 on 2020-06-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedvariantattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='assignedvariantattribute',
            name='values',
            field=models.ManyToManyField(to='attributes.AttributeValue'),
        ),
    ]
